Filter out photos of current user #12
vlle/Photoshnaya pull request #21
Opened 2023-11-01 20:15 UTC by detchenkov

Take current user tg_id and filter photos using that id.
In the tests calling function with user_id = -1 to not filter any lines.

2023-11-05 20:24 UTC, detchenkov commented
#12

2023-11-06 18:15 UTC, vlle requested changes
все ок, две мелких правки чтобы код симпатичнее вышел и вмержу

2023-11-06 18:15 UTC, vlle commented on app/db/db_operations.py
Тут лучше убрать двойное вложение and_ друг в друга, в and_ может быть много bool условий. 

```python
                and_(
                        group_photo.c.group_id
                        == (
                            select(Group.id)
                            .where(Group.telegram_id == group_id)
                            .scalar_subquery()
                        ),
                    Photo.id > current_photo,
                    User.telegram_id != user_id
                )
            )
```

2023-11-06 18:15 UTC, vlle commented on app/tests/test_db.py
Тут давай вынесем -1 в константную переменную сверху в файлике
в подобном формате

```python
USER_STUB = -1
```

2023-11-06 21:02 UTC, closed without merging