Keep own photo but forbid to vote for it
vlle/Photoshnaya pull request #23
Opened 2023-11-07 19:44 UTC by detchenkov

для #12 переделал - оставил фото, но при попытке голосовать появляется сообщение о том что нельзя.

2023-11-07 20:09 UTC, vlle requested changes
Все ок, только сделай еще тест плиз.  Чтоб потом не потереть случайно проверку эту, мало ли что


Можешь прям в tests_db засунуть, ты видел примеры

2023-11-12 17:27 UTC, vlle commented on app/tests/test_db.py
> +    await like.like_photo_with_file_id(users[0].telegram_id, all_photo_ids[0])  #doesn't count as it's a like for own photo
Здесь и далее в тестах: а сделай assert на этот кейс для большей наглядности. Там же возвращается -1 когда самолайк происходит. -1 можно вынести константой для большей читаемости. 

```python
error = await like.like_photo_with_file_id(users[0].telegram_id, all_photo_ids[0])
assert error != SELF_LIKE
```

2023-11-12 20:20 UTC, detchenkov commented on app/tests/test_db.py
> +    await like.like_photo_with_file_id(users[0].telegram_id, all_photo_ids[0])  #doesn't count as it's a like for own photo
Сделано

2023-11-14 08:43 UTC, vlle approved these changes
lgtm

2023-11-14 08:53 UTC, merged